server:
  port: 8080
spring:
  application:
    name: hospital-oop
  datasource:
    url: jdbc:mysql://localhost:3306/hastane?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 158358.asd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
